apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-thymeleaf
  name: spring-thymeleaf-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30000
    port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    app: spring-thymeleaf
  type: NodePort

